version: "3.0"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate && python manage.py runserver 0.0.0.0:8888"